using System;
using System.Collections.Generic;
using System.Linq;
using DotaTranspiler.IR;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DotaTranspiler
{
    /// <summary>
    /// Transforms one ClassInfo into a LuaFile.
    ///
    /// Phase 2 additions over Phase 1:
    ///   - Modifier: generates DeclareFunctions() from [ModifierProperty] methods
    ///   - Modifier: generates CheckState() from [ModifierState] methods
    ///   - Modifier: OnIntervalThink and property getters treated as hot-path
    ///     (no DotaCompat wrapper, no unnecessary locals)
    ///   - Ability: emits empty lifecycle stubs for any missing standard methods
    ///   - GameMode: emits InitGameMode wiring comment
    ///   - ListenToGameEvent calls: self-context binding
    ///   - Enum member access: AbilityBehavior.X → integer value
    /// </summary>
    public sealed class ClassEmitter
    {
        private readonly SemanticModel _model;
        private readonly bool _emitDebugComments;
        private const string Namespace = "Addon";

        // Standard lifecycle methods for each class kind.
        // Any of these that the user has NOT declared get an empty stub emitted.
        private static readonly IReadOnlyList<string> AbilityLifecycle = new[]
        {
            "OnSpellStart",
            "OnAbilityPhaseStart",
            "OnAbilityPhaseInterrupted",
            "OnProjectileHit",
            "GetBehavior",
            "GetCastRange",
        };

        private static readonly IReadOnlyList<string> ModifierLifecycle = new[]
        {
            "OnCreated",
            "OnRefresh",
            "OnRemoved",
            "OnIntervalThink",
            "IsDebuff",
            "IsPurgable",
            "GetAttributes",
        };

        public ClassEmitter(SemanticModel model, bool emitDebugComments = false)
        {
            _model = model;
            _emitDebugComments = emitDebugComments;
        }

        public LuaFile Emit(ClassInfo info)
        {
            var nodes = new List<LuaNode>();

            // ── File header ──────────────────────────────────────────────────
            nodes.Add(new LuaComment("Generated by DotaTranspiler"));
            nodes.Add(new LuaComment($"Source: {System.IO.Path.GetFileName(info.SourceFile)}"));
            nodes.Add(new LuaComment($"Class:  {info.LuaName} ({info.Kind})"));

            // ── DotaCompat locals (only for non-hot-path methods) ────────────
            // Hot-path methods (OnIntervalThink, property getters) never call these.
            // We still localize IsValid for use in regular methods.
            nodes.Add(new LuaLocalDecl(
                new[] { "IsValid" },
                new[] { (LuaNode)new LuaMemberAccess(
                    new LuaIdentifier("DotaCompat"), "IsValid") }));

            // ── class({}) declaration ────────────────────────────────────────
            var defaultFields = CollectDefaultFields(info.Syntax);
            nodes.Add(new LuaClassDecl(info.LuaName, defaultFields));

            // ── Modifier-specific generated methods ──────────────────────────
            if (info.Kind == DotaClassKind.Modifier)
            {
                if (info.PropertyMethods.Count > 0)
                    nodes.Add(EmitDeclareFunctions(info));

                if (info.StateMethods.Count > 0)
                    nodes.Add(EmitCheckState(info));
            }

            // ── User-declared methods ────────────────────────────────────────
            var declaredNames = new HashSet<string>();
            foreach (var method in info.Syntax.Members.OfType<MethodDeclarationSyntax>())
            {
                declaredNames.Add(method.Identifier.Text);
                foreach (var node in EmitMethod(info.LuaName, method, info))
                    nodes.Add(node);
            }

            // ── Lifecycle stubs for missing standard methods ─────────────────
            var lifecycle = info.Kind == DotaClassKind.Ability ? AbilityLifecycle
                          : info.Kind == DotaClassKind.Modifier ? ModifierLifecycle
                          : Array.Empty<string>();

            foreach (var name in lifecycle)
            {
                if (!declaredNames.Contains(name))
                    nodes.Add(EmitEmptyStub(info.LuaName, name, GetDefaultStubBody(name)));
            }

            // ── Namespace alias ──────────────────────────────────────────────
            nodes.Add(new LuaNamespaceAlias(Namespace, info.LuaName));

            return new LuaFile(info.ScriptFilePath, nodes);
        }

        // ─────────────────────────────────────────────────────────────────────
        // DeclareFunctions() — generated from [ModifierProperty] methods
        // ─────────────────────────────────────────────────────────────────────

        private LuaFunctionDecl EmitDeclareFunctions(ClassInfo info)
        {
            var fields = info.PropertyMethods
                .Select(p => new LuaTableField(
                    new LuaIdentifier(p.PropertyConstant),
                    new LuaIdentifier(p.PropertyConstant),
                    indexKey: false))
                // Table fields where key == value means array-style: just the constant
                .Select(f => new LuaTableField(f.Value))
                .ToList();

            var body = new LuaBlock(new[]
            {
                (LuaNode)new LuaReturn(new[]
                {
                    (LuaNode)new LuaTableConstructor(fields)
                })
            });

            return new LuaFunctionDecl(
                info.LuaName, "DeclareFunctions",
                isInstanceMethod: true,
                Array.Empty<string>(),
                body,
                _emitDebugComments ? "[generated: DeclareFunctions]" : null);
        }

        // ─────────────────────────────────────────────────────────────────────
        // CheckState() — generated from [ModifierState] methods
        // ─────────────────────────────────────────────────────────────────────

        private LuaFunctionDecl EmitCheckState(ClassInfo info)
        {
            // Each entry: [MODIFIER_STATE_X] = <return value of the C# method>
            var fields = new List<LuaTableField>();
            foreach (var entry in info.StateMethods)
            {
                // Find the method body to inline its return value
                var methodSyntax = info.Syntax.Members
                    .OfType<MethodDeclarationSyntax>()
                    .FirstOrDefault(m => m.Identifier.Text == entry.MethodName);

                LuaNode value;
                if (methodSyntax?.ExpressionBody != null)
                {
                    var transformer = new BodyTransformer(_model, false);
                    value = transformer.TransformExpression(
                        methodSyntax.ExpressionBody.Expression);
                }
                else if (methodSyntax?.Body?.Statements.Count == 1
                    && methodSyntax.Body.Statements[0] is ReturnStatementSyntax ret
                    && ret.Expression != null)
                {
                    var transformer = new BodyTransformer(_model, false);
                    value = transformer.TransformExpression(ret.Expression);
                }
                else
                {
                    // Default to false if we can't inline
                    value = LuaFalse.Instance;
                }

                fields.Add(new LuaTableField(
                    new LuaIdentifier(entry.StateConstant), value, indexKey: true));
            }

            var body = new LuaBlock(new[]
            {
                (LuaNode)new LuaReturn(new[]
                {
                    (LuaNode)new LuaTableConstructor(fields)
                })
            });

            return new LuaFunctionDecl(
                info.LuaName, "CheckState",
                isInstanceMethod: true,
                Array.Empty<string>(),
                body,
                _emitDebugComments ? "[generated: CheckState]" : null);
        }

        // ─────────────────────────────────────────────────────────────────────
        // Default fields from C# field declarations
        // ─────────────────────────────────────────────────────────────────────

        private IReadOnlyList<LuaTableField> CollectDefaultFields(ClassDeclarationSyntax cls)
        {
            var fields = new List<LuaTableField>();
            foreach (var member in cls.Members.OfType<FieldDeclarationSyntax>())
            {
                foreach (var v in member.Declaration.Variables)
                {
                    if (v.Initializer == null) continue;

                    if (v.Initializer.Value is LiteralExpressionSyntax lit)
                    {
                        var value = TransformLiteralAsDefault(lit);
                        if (value != null)
                            fields.Add(new LuaTableField(v.Identifier.Text, value));
                    }
                }
            }
            return fields;
        }

        private static LuaNode? TransformLiteralAsDefault(LiteralExpressionSyntax lit) =>
            lit.Kind() switch
            {
                SyntaxKind.NumericLiteralExpression =>
                    new LuaNumber(Convert.ToDouble(lit.Token.Value)),
                SyntaxKind.StringLiteralExpression =>
                    new LuaString(lit.Token.ValueText),
                SyntaxKind.TrueLiteralExpression => LuaTrue.Instance,
                SyntaxKind.FalseLiteralExpression => LuaFalse.Instance,
                SyntaxKind.NullLiteralExpression => LuaNil.Instance,
                _ => null
            };

        // ─────────────────────────────────────────────────────────────────────
        // Method emission
        // ─────────────────────────────────────────────────────────────────────

        private IEnumerable<LuaNode> EmitMethod(
            string className,
            MethodDeclarationSyntax method,
            ClassInfo info)
        {
            // Skip abstract/extern stubs (DotaApi interface methods)
            if (method.Body == null && method.ExpressionBody == null) yield break;
            if (method.Modifiers.Any(m => m.IsKind(SyntaxKind.AbstractKeyword))) yield break;

            // Skip [ModifierState] methods — their bodies are inlined into CheckState()
            if (HasAttribute(method, "ModifierState") || HasAttribute(method, "ModifierStateAttribute"))
                yield break;

            var methodName = method.Identifier.Text;
            bool isStatic = method.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword));
            bool isHotPath = info.HotPathMethods.Contains(methodName);

            var parameters = method.ParameterList.Parameters
                .Select(p => p.Identifier.Text)
                .ToList();

            LuaBlock body;

            if (method.Body != null)
            {
                // Hot-path: suppress debug comments for tight loops
                var transformer = new BodyTransformer(_model,
                    _emitDebugComments && !isHotPath);
                var stmts = transformer.TransformBlock(method.Body);
                body = new LuaBlock(stmts);
            }
            else if (method.ExpressionBody != null)
            {
                var transformer = new BodyTransformer(_model, false);
                var expr = transformer.TransformExpression(
                    method.ExpressionBody.Expression);
                body = new LuaBlock(new[] { (LuaNode)new LuaReturn(new[] { expr }) });
            }
            else
            {
                body = new LuaBlock(Array.Empty<LuaNode>());
            }

            string? sourceComment = null;
            if (_emitDebugComments && !isHotPath)
            {
                var line = method.GetLocation().GetLineSpan().StartLinePosition.Line + 1;
                var file = System.IO.Path.GetFileName(
                    method.GetLocation().GetLineSpan().Path);
                sourceComment = $"[{file}:{line}]";
            }

            yield return new LuaFunctionDecl(
                className, methodName,
                isInstanceMethod: !isStatic,
                parameters, body, sourceComment);
        }

        private static LuaFunctionDecl EmitEmptyStub(
            string className, string methodName, LuaNode? defaultReturn = null)
        {
            var stmts = new List<LuaNode>();
            if (defaultReturn != null)
                stmts.Add(new LuaReturn(new[] { defaultReturn }));

            return new LuaFunctionDecl(
                className, methodName,
                isInstanceMethod: true,
                Array.Empty<string>(),
                new LuaBlock(stmts));
        }

        /// <summary>
        /// Returns a sensible default return value for lifecycle stub methods
        /// where Dota expects a specific type back.
        /// </summary>
        private static LuaNode? GetDefaultStubBody(string methodName) => methodName switch
        {
            "OnAbilityPhaseStart" => LuaTrue.Instance,
            "OnProjectileHit" => LuaFalse.Instance,
            "GetBehavior" =>
                new LuaIdentifier("DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"),
            "GetCastRange" => new LuaNumber(600),
            "IsDebuff" => LuaFalse.Instance,
            "IsPurgable" => LuaTrue.Instance,
            "GetAttributes" =>
                new LuaIdentifier("MODIFIER_ATTRIBUTE_NONE"),
            _ => null
        };

        private static bool HasAttribute(MethodDeclarationSyntax method, string attrName) =>
            method.AttributeLists
                .SelectMany(al => al.Attributes)
                .Any(a => a.Name.ToString().Replace("Attribute", "") == attrName
                       || a.Name.ToString() == attrName);
    }
}
